replicaCount: 3

image:
  repository: public.ecr.aws/x1u4e0v6/nginx
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: { }

podAnnotations:
  app.kubernetes.io/team: hello

podSecurityContext: { }

securityContext:
  allowPrivilegeEscalation: false

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: hello-terraform.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: hello-tls
      hosts:
        - hello-terraform.com

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 12
  targetCPUUtilizationPercentage: 50

nodeSelector: { }

tolerations: [ ]

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - hello
          topologyKey: kubernetes.io/hostname
        weight: 9
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - hello
          topologyKey: topology.kubernetes.io/zone
        weight: 10
